# Generated by Django 5.2.9 on 2026-01-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "stars",
                    models.CharField(
                        choices=[
                            ("1", "ONE"),
                            ("2", "TWO"),
                            ("3", "THREE"),
                            ("4", "FOUR"),
                            ("5", "FIVE"),
                        ]
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "student_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("headline", models.CharField(blank=True, max_length=30)),
                (
                    "tutor_description",
                    models.CharField(
                        choices=[
                            ("EN", "ENGLISH"),
                            ("SP", "SPANISH"),
                            ("IT", "ITALIAN"),
                            ("GR", "GERMAN"),
                            ("FR", "FRENCH"),
                        ],
                        max_length=2,
                    ),
                ),
                ("profile_pic", models.ImageField(upload_to="pp")),
                ("website", models.URLField(blank=True, null=True)),
                ("x", models.URLField(blank=True, null=True)),
                ("linkdin", models.URLField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(unique=True)),
                ("subtitle", models.CharField()),
                ("description", models.TextField()),
                (
                    "notes_types",
                    models.TextField(choices=[("PD", "PDF"), ("PT", "PPT")]),
                ),
                ("notes_desc", models.TextField()),
                ("file", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="thumbnail/")),
                ("course_overview", models.TextField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor",
                        to="api.tutor",
                    ),
                ),
            ],
        ),
    ]
