# Generated by Django 5.2.9 on 2026-01-18 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('title', models.CharField(unique=True)),
                ('about_course', models.TextField(default='')),
                ('course_description', models.TextField(default=True)),
                ('certification', models.TextField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/')),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('German', 'German'), ('French', 'French')], default='English')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('stars', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR'), ('5', 'FIVE')])),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_table', to='api.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=True)),
                ('subtitle', models.TextField(default=True)),
                ('desciption', models.TextField(default=True)),
                ('chapter_overview', models.TextField(default='')),
                ('key_learnings', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('headline', models.CharField(blank=True, max_length=30)),
                ('tutor_description', models.CharField(default='')),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('German', 'German'), ('French', 'French')], default='EN')),
                ('image_label', models.CharField(default='profile', max_length=20)),
                ('profile_pic', models.ImageField(upload_to='pics/')),
                ('areas_of_experience', models.TextField(default='')),
                ('professional_experience', models.TextField(default='')),
                ('website', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='api.tutor'),
        ),
    ]
