# Generated by Django 5.2.9 on 2026-01-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="key_learnings",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="courses",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tutor",
            name="about_you",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tutor",
            name="areas_of_experience",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tutor",
            name="professional_experience",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="courses",
            name="course_overview",
            field=models.TextField(default=""),
        ),
    ]
