# Generated by Django 5.2.9 on 2026-01-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_courses_key_learnings_courses_price_tutor_about_you_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="about_you",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="user",
        ),
        migrations.AddField(
            model_name="comments",
            name="course",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_table",
                to="api.courses",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="image_label",
            field=models.CharField(default="profile", max_length=20),
        ),
        migrations.AddField(
            model_name="tutor",
            name="language",
            field=models.CharField(
                choices=[
                    ("EN", "ENGLISH"),
                    ("SP", "SPANISH"),
                    ("IT", "ITALIAN"),
                    ("GR", "GERMAN"),
                    ("FR", "FRENCH"),
                ],
                default="EN",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="file",
            field=models.FileField(upload_to="course_files/"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="notes_types",
            field=models.CharField(choices=[("PD", "PDF"), ("PT", "PPT")]),
        ),
        migrations.AlterField(
            model_name="courses",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnail/"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="profile_pic",
            field=models.ImageField(upload_to="pics/"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="tutor_description",
            field=models.CharField(default=""),
        ),
    ]
