# Generated by Django 5.2.9 on 2026-01-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_tutor_about_you_remove_tutor_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Spanish", "Spanish"),
                    ("Italian", "Italian"),
                    ("German", "German"),
                    ("French", "French"),
                ],
                default="EN",
            ),
        ),
    ]
