# Generated by Django 5.2.9 on 2026-01-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
