# Generated by Django 5.2.9 on 2026-01-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tutor_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('subtitle', models.TextField(default='')),
                ('desciption', models.TextField(default='')),
                ('notes_content_type', models.CharField()),
                ('notes_type', models.TextField()),
                ('notes_description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
