# Generated by Django 5.2.9 on 2026-01-14 04:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chapters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_overview',
            new_name='about_course',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='notes_content_type',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='notes_description',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='notes_type',
        ),
        migrations.RemoveField(
            model_name='chapters',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='file',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='key_learnings',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='notes_desc',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='notes_types',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='chapters',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.courses'),
        ),
        migrations.AddField(
            model_name='chapters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='certification',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='desciption',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='subtitle',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='title',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapters')),
            ],
        ),
    ]
