# Generated by Django 5.2.9 on 2026-01-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_course_overview_courses_about_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='chapter_overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chapters',
            name='key_learnings',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('German', 'German'), ('French', 'French')], default='English'),
        ),
    ]
